# Generated by Django 5.1.1 on 2024-09-10 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre_eps', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=50)),
                ('apellido_paciente', models.CharField(max_length=50)),
                ('tipo_identificacion', models.CharField(max_length=10, unique=True)),
                ('numero_identificacion', models.IntegerField()),
                ('edad_paciente', models.IntegerField()),
                ('genero_paciente', models.CharField(max_length=10)),
                ('direccion_paciente', models.CharField(max_length=100)),
                ('telefono_paciente', models.CharField(max_length=10)),
                ('correo_paciente', models.EmailField(max_length=254)),
                ('tipo_sangre', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='eps_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Usuario Activo'), ('inactivo', 'Usuario Inactivo'), ('bloqueado', 'Usuario Bloqueado')], max_length=20)),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision.eps')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision.paciente')),
            ],
        ),
    ]
