# Generated by Django 5.1.1 on 2024-09-12 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historia_clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_historia', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=500)),
                ('motivo_salida', models.CharField(blank=True, max_length=500, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision.paciente')),
            ],
        ),
    ]
