# Generated by Django 5.1.1 on 2024-09-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0002_historia_clinica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historia_clinica',
            old_name='motivo',
            new_name='motivo_ingreso',
        ),
    ]
