# Generated by Django 5.1.1 on 2024-09-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0003_rename_motivo_historia_clinica_motivo_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eps_paciente',
            name='estado',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_identificacion',
            field=models.CharField(max_length=10),
        ),
    ]
