# Generated by Django 5.1.1 on 2024-09-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0005_remove_paciente_numero_identificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='numero_identificacion',
            field=models.BigIntegerField(default=0),
        ),
    ]
