# Generated by Django 5.1.1 on 2024-09-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0006_paciente_numero_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_clinica',
            name='numero_historia',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo_paciente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
